language: go
cache:
  directories:
    - $GOCACHE
    - $GOPATH/pkg/mod
    - $GOPATH/src/github.com/btcsuite
    - $GOPATH/src/github.com/golang
    - $GOPATH/src/gopkg.in/alecthomas
go:
  - "1.11.x"
sudo: false
install:
  - export PATH=$PATH:$PWD/linux-amd64/
  - mkdir -p $GOPATH/src/github.com/btcsuite/
  - go get -d github.com/litecoinfinance/btcd
  - pushd $GOPATH/src/github.com/litecoinfinance/btcd
  - $GOPATH/src/github.com/litecoinfinance/neutrino/btcd_checkout.sh
  - go install . ./cmd/...
  - popd
env:
  matrix:
    - RACE=false
    - RACE=true
script:
  - export GO111MODULE=on
  - export PATH=$PATH:$GOPATH/bin
  - ./gotest.sh
